// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMfFmZYcypcbyzVR9Kv9XJ5JQVGTLBUKE',
    appId: '1:502594603175:web:c7026337712eae0a103382',
    messagingSenderId: '502594603175',
    projectId: 'authnew-f163d',
    authDomain: 'authnew-f163d.firebaseapp.com',
    storageBucket: 'authnew-f163d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-89KBZOWLt1GxBG-HI5Q2_sPWspjpdfw',
    appId: '1:502594603175:android:0474b446dcb3b0af103382',
    messagingSenderId: '502594603175',
    projectId: 'authnew-f163d',
    storageBucket: 'authnew-f163d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0DspAuafLjBpSXRli-DbkpwQCXpb2mI',
    appId: '1:502594603175:ios:1125eb70d55aff99103382',
    messagingSenderId: '502594603175',
    projectId: 'authnew-f163d',
    storageBucket: 'authnew-f163d.appspot.com',
    iosBundleId: 'com.example.ticketapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0DspAuafLjBpSXRli-DbkpwQCXpb2mI',
    appId: '1:502594603175:ios:1125eb70d55aff99103382',
    messagingSenderId: '502594603175',
    projectId: 'authnew-f163d',
    storageBucket: 'authnew-f163d.appspot.com',
    iosBundleId: 'com.example.ticketapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMfFmZYcypcbyzVR9Kv9XJ5JQVGTLBUKE',
    appId: '1:502594603175:web:43f5a91926c95c18103382',
    messagingSenderId: '502594603175',
    projectId: 'authnew-f163d',
    authDomain: 'authnew-f163d.firebaseapp.com',
    storageBucket: 'authnew-f163d.appspot.com',
  );
}
